version: "3"
services:

  db:
    image: docker.io/jjclavijo/dafne-db:times-latest
#    build: ./db
#    volumes:
#      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "127.0.0.1:5432:5432" # Expose port for Debug purposes
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      POSTGRES_PASSWORD: "docker"

  model:
    image: tensorflow/serving:2.3.0
    volumes:
      - $DAFNE_HOME/saved_models/:/models/
    command: ["--model_config_file=/models/models.config", 
              "--model_config_file_poll_wait_seconds=60",
              "--rest_api_port=8501"]
    networks:
      - backend
    
  shower:
    image: dafne-apps:serving-latest
#    build: ./data_feeder
    volumes:
      - $DAFNE_HOME/data/http-nevada:/opt/app/data
    networks:
      - backend
    links:
      - db:db
      - model:tfserving
    environment:
      SI_SOCKDIR: "/sockets/"
      DAFNE_HOME: "/"
      LOCAL_USER_ID: "${LOCAL_USER_ID:-1000}"
      DAFNE_DB:  "host='db' port=5432 user='postgres' password='docker' dbname='sismoident'"
      SERVING_HOST: "tfserving"
      SERVING_PORT: "8501"
      SERVING_PATH: "v1/models"
    ports:
      - "127.0.0.1:8080:8080"

networks:
  backend:

#volumes:
  #db-data:
  #sockets:
  #data-files:
