name:                dfdf
version:             0.1.0.0
github:              "githubuser/dfdf"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/dfdf#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- servant-client
- servant-js
- servant
- wai
- warp
- text
- lzma
- bytestring
- mtl
- postgresql-simple
- time
- stringsearch
- utf8-string
- async
- http-client
- template
- raw-strings-qq
- filepath

library:
  source-dirs: src

executables:
  dfdf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - base
    - dfdf
